name: build

on:
  push:
    branches:
      - main

env:
  IMAGEREPO: filstimatias/gitops-goapp
  GITREPO: matiasfilsti/gitops-argocd
  USRMAIL: mf@gmail.com
  USR: mfilsti

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGEREPO }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: build and push to docker
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
           ${{ steps.meta.outputs.tags }} 
           ${{ env.IMAGEREPO }}:${{ github.sha }}
  deploy-staging:
    needs: build
    environment: Staging
    runs-on: ubuntu-latest
    steps:
    - name: changing the deployment of git repo
      uses: actions/checkout@v4
      with:
        repository: '${{ env.GITREPO }}'
        token: ${{ secrets.GIT_PASSWORD }}
    - name: modify the image
      run: |
        git config user.email '$USRMAIL'
        git config user.name '$USR'
        ls -la
        pwd
        cd ${{ env.GITOPSDIR }}
        pwd
        cat kustomization.yaml
        sed -i 's/newTag: .*/newTag: ${{ github.sha }}/' kustomization.yaml
        cat kustomization.yaml
        git add .
        git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
        git push origin main
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        RUN_NUMBER: ${{ github.run_number }}
  deploy-production:
    needs: deploy-staging
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: changing the deployment of git repo
      uses: actions/checkout@v4
      with:
        repository: '${{ env.GITREPO }}'
        token: ${{ secrets.GIT_PASSWORD }}
    - name: modify the image
      run: |
        git config user.email '$USRMAIL'
        git config user.name '$USR'
        ls -la
        pwd
        cd ${{ env.GITOPSDIR }}
        pwd
        cat kustomization.yaml
        sed -i 's/newTag: .*/newTag: ${{ github.sha }}/' kustomization.yaml
        cat kustomization.yaml
        git add .
        git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
        git push origin main
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        RUN_NUMBER: ${{ github.run_number }}